### ISSUE TITLE
product_multi_ean changes column type

### ISSUE THREAD

**Issue by gurneyalex** [OCA/stock-logistics-barcode#52] opened 2016-11-14 09:50 UTC
Module product_multi_ean in branch 7.0 and 8.0 changes a column type (product.product ean13 changes from char to m2o). This is not a nice thing to do as it breaks any module which is not depending on product_multi_ean and needs to create products with an ean13 field (in demo data or tests). 

This kind of db layout changes should be avoided. 

Options: 
* remove product_multi_ean from OCA
* change the db layout for product_multi_ean to restore the ean13 field as a char field (and add another field to access the main ean13) (but this can break module depending on product_multi_ean on some installation)
* not sure

Changing the db layout of the module in 9.0 and 10.0 is easy to do as the module has not yet been ported. The main question is for 7.0 and 8.0.

**Comment by gurneyalex** [comment] 2016-11-14 09:50
ping @guewen @legalsylvain @OCA/logistics-maintainers

**Comment by legalsylvain** [comment] 2016-11-14 10:07
Hi, 

**V7**  
- in Core, it is a Char [Ref](https://github.com/odoo/odoo/blob/7.0/addons/product/product.py#L563)
- in product_multi_ean, it is a **Many2one** (computed) [ref](https://github.com/OCA/stock-logistics-barcode/blob/7.0/product_multi_ean/product_ean.py#L122)

-> problem

**V8** 
- in Core, it is a Char [Ref](https://github.com/odoo/odoo/blob/8.0/addons/product/product.py#L1001)
- in product_multi_ean, it is a Char (computed) [ref](https://github.com/OCA/stock-logistics-barcode/blob/8.0/product_multi_ean/models/product_product.py#L50)

-> So I did not test, but it should not be a problem in V8.0

**V9 / V10**
- In core, the field is a Char. (now named 'barcode').
  - product_multi_ean is unported.

-> No problem.

About your options
- The first one should break installation based on OCA branches, without specific revision defined. (buildout deployment pointing on 7.0 serie for exemple)
- The second one will break installation too.
- I see a third one, but not sure it is ok. Just set this module as installable to False. Consequences
  - Fix Travis / Runbot
  - Not installable anymore
  - Existing deployment should still work. (but not sure, just a guess).

kind regards.

**Comment by gurneyalex** [comment] 2016-11-14 10:12
ok so the problem was identified at the time of the v8 migration and solved there, without touching the 7.0 branch.

**Comment by legalsylvain** [comment] 2016-11-14 10:59
> I see a third one, but not sure it is ok. Just set this module as installable to False.

Tested, it doesn't work. This intent will break at the next update all, because loading the module will be skipped. odoo update is based on the manifests. [Ref](https://github.com/odoo/odoo/blob/7.0/openerp/modules/graph.py#L102)

If any people has an idea how to monkey patch this part, in 'product_multi_ean'. What we want is "if the module is installed on an instance, and the manifest of this module is set installable to False, this module is loaded". (Avoid breaking production)

**Comment by pedrobaeza** [comment] 2016-11-14 11:15
I think it's better to change the type again to Char in v7.

**Comment by legalsylvain** [comment] 2016-11-18 11:14
Hi @pedrobaeza.

Changing the type to char in v7 will take more time (analysis + upgrade migration script), and it will break all dependencies. (as the other solutions).

**Comment by pedrobaeza** [comment] 2016-11-18 11:49
What are the dependencies currently? The migration script is very simple IMO.

**Comment by legalsylvain** [comment] 2016-11-18 12:20
- Dependencies could be in custom module. We don't know.
- Well, in fact this bug occures because i began to share my work scan_to_inventory module (#50) after an email of @rafaelbn. I wanted to have my module working on runbot to show how it works to the community. My module does not work on runbot if product_multi_ean (V7) is installed.

In fact, no module are working with product_multi_ean module installed ! Including core module like point_of_sale. This module completely breaks product ean feature by design. And I really have no time to fix product_multi_ean buggy module.

For that reason, my preference goes to just set 'installable' to False in product_multi_ean manifest and adding a comment in the module description. If by chance, this module is used on a production system, based on HEAD of this branch, it will be very easy for the maintainer to set installable to True again, patching his code.

Kind regards.

**Comment by legalsylvain** [comment] 2016-12-01 15:23
Fixed by #57

**Closed as completed by legalsylvain** 2016-12-01 15:23 UTC
