### ISSUE TITLE
barcodes_generator_partner not available on pypi for v12

### ISSUE THREAD

**Issue by eLBati** [OCA/stock-logistics-barcode#246] opened 2020-01-30 16:19 UTC
https://pypi.org/project/odoo12-addon-barcodes-generator-partner/ page not found

**Comment by eLBati** [comment] 2020-01-30 16:19
@sbidoul do you know why?
Thanks

**Comment by sbidoul** [comment] 2020-01-30 18:15
I see nothing obvious and no error in the bot log... strange

**Comment by pedrobaeza** [comment] 2020-01-30 18:43
I think it has been the problem with the readme. See my comment in the PR

**Comment by sbidoul** [comment] 2020-01-30 20:50
So it should land on PyPI tomorrow.

**Comment by sbidoul** [comment] 2020-01-30 20:52
See also discussion in #244 and https://github.com/OCA/maintainer-tools/issues/441 for the root cause.

**Comment by sbidoul** [comment] 2020-01-30 21:22
@eLBati further digging into this. Actually the real reason it is not on PyPI is that the pypi publishing occurs on a nightly basis. 

But it was not on https://wheelhouse.odoo-community.org/oca-simple/ either. And the reason for that is that #244 was merged without bumping version and in that case the wheel generator does not kick in immediately, it waits for the nightly batch. This touches the issue of generating a round version number in migration commits...

**Closed as completed by sbidoul** 2020-01-30 21:22 UTC

**Comment by eLBati** [comment] 2020-01-31 09:30
Thanks!
